In [42]:
pip install geopy

Requirement already satisfied: geopy in c:\users\vasyl\anaconda3\lib\site-packages (2.3.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\vasyl\anaconda3\lib\site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

In [43]:
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
import pandas as pd

In [44]:
df = pd.read_csv('Cities.csv')

In [45]:
geolocator = Nominatim(timeout=10, user_agent = "my-App")

In [46]:
df['Combined'] = df['State '].astype(str) +', '+ df['City']

In [47]:
df=df.drop('Location', axis=1)

In [48]:
df

,2021 rank,State,City,2020 population density,2020 population density(Km2),2021 estimate,2020 census,2020 land area (sq mi),2020 land area (Km2),Change,Combined
0,1.0,New York,New York,"29,298/sq mi","11,312/km","8,467,513","8,804,190",300.5 sq mi,778.3 km,−3.82%,"New York, New York"
1,2.0,California,Los Angeles,"8,304/sq mi","3,206/km","3,849,297","3,898,747",469.5 sq mi,"1,216.0 km",−1.27%,"California, Los Angeles"
2,3.0,Illinois,Chicago,"12,061/sq mi","4,657/km","2,696,555","2,746,388",227.7 sq mi,589.7 km,−1.81%,"Illinois, Chicago"
3,4.0,Texas,Houston,"3,599/sq mi","1,390/km","2,288,250","2,304,580",640.4 sq mi,"1,658.6 km",−0.71%,"Texas, Houston"
4,5.0,Arizona,Phoenix,"3,105/sq mi","1,199/km","1,624,569","1,608,139",518.0 sq mi,"1,341.6 km",+1.02%,"Arizona, Phoenix"
...,...,...,...,...,...,...,...,...,...,...,...
328,329.0,Colorado,Longmont,"3,434/sq mi","1,326/km","100,758","98,885",28.8 sq mi,74.6 km,+1.89%,"Colorado, Longmont"
329,330.0,Alabama,Tuscaloosa,"1,609/sq mi",621/km,"100,618","99,600",61.9 sq mi,160.3 km,+1.02%,"Alabama, Tuscaloosa"
330,331.0,California,Norwalk,"10,595/sq mi","4,091/km","100,373","102,773",9.7 sq mi,25.1 km,−2.34%,"California, Norwalk"
331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,NaN,NaN,https://www.downloadexcelfiles.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"nan, https://www.downloadexcelfiles.com/"

In [49]:
latitudes = []
longitudes = []

In [50]:
for address in df['Combined']:
    try:
        location = geolocator.geocode(address)
        if location is not None:
            latitudes.append(location.latitude)
            longitudes.append(location.longitude)
        else:
            latitudes.append(None)
            longitudes.append(None)
    except GeocoderTimedOut:
        latitudes.append(None)
        longitudes.append(None)
        print('Geocoding service timed out for address:', address)

In [51]:
df['Latitude'] = latitudes
df['Longitude'] = longitudes

In [52]:
df

,2021 rank,State,City,2020 population density,2020 population density(Km2),2021 estimate,2020 census,2020 land area (sq mi),2020 land area (Km2),Change,Combined,Latitude,Longitude
0,1.0,New York,New York,"29,298/sq mi","11,312/km","8,467,513","8,804,190",300.5 sq mi,778.3 km,−3.82%,"New York, New York",40.712728,-74.006015
1,2.0,California,Los Angeles,"8,304/sq mi","3,206/km","3,849,297","3,898,747",469.5 sq mi,"1,216.0 km",−1.27%,"California, Los Angeles",34.053691,-118.242766
2,3.0,Illinois,Chicago,"12,061/sq mi","4,657/km","2,696,555","2,746,388",227.7 sq mi,589.7 km,−1.81%,"Illinois, Chicago",41.875562,-87.624421
3,4.0,Texas,Houston,"3,599/sq mi","1,390/km","2,288,250","2,304,580",640.4 sq mi,"1,658.6 km",−0.71%,"Texas, Houston",29.758938,-95.367697
4,5.0,Arizona,Phoenix,"3,105/sq mi","1,199/km","1,624,569","1,608,139",518.0 sq mi,"1,341.6 km",+1.02%,"Arizona, Phoenix",33.448437,-112.074141
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,329.0,Colorado,Longmont,"3,434/sq mi","1,326/km","100,758","98,885",28.8 sq mi,74.6 km,+1.89%,"Colorado, Longmont",40.167212,-105.101929
329,330.0,Alabama,Tuscaloosa,"1,609/sq mi",621/km,"100,618","99,600",61.9 sq mi,160.3 km,+1.02%,"Alabama, Tuscaloosa",33.209561,-87.567526
330,331.0,California,Norwalk,"10,595/sq mi","4,091/km","100,373","102,773",9.7 sq mi,25.1 km,−2.34%,"California, Norwalk",33.909280,-118.084917
331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.314475,11.048029
332,NaN,NaN,https://www.downloadexcelfiles.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"nan, https://www.downloadexcelfiles.com/",NaN,NaN